{% set name = "gds-lsmp" %}
{% set version = "2.19.9" %}

# dependencies
{% set gds_base_version = "2.19.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: f8d19fe501788de293a49c160ecea2d16e4feea49ca0e8ec679600703d6632ed
  patches:
    # hack the build to make it think we're using macports
    # see https://git.ligo.org/gds/gds/-/issues/69
    - macos-building_macports.patch  # [osx]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("gds-lsmp", max_pin="x.x") }}
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - make
    - pkg-config
  host:
    - gds-base >={{ gds_base_version }}
  run:
    - gds-base >={{ gds_base_version }}

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --print-errors --exact-version {{ version }} liblsmp
    - lsmp_mux --help  # [not osx]

about:
  home: http://www.lsc-group.phys.uwm.edu/daswg/projects/dmt.html
  dev_url: https://git.ligo.org/gds/gds.git
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: GDS package lsmp libraries
  description: |
    LSMP libraries required by the rest of the GDS packages

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
